### ISSUE TITLE
How Do I Get Emoji Support in my Console?

### ISSUE THREAD

**Issue by ardalis** [khalidabuhakmeh/GameOfLife#1]
All I see is ??? everywhere:
![image](https://user-images.githubusercontent.com/782127/80388053-68dcad80-8877-11ea-906f-491f75309c53.png)

I tried Windows cmd and Powershell. Same in both. Where should this work? Want to add a README with setup instructions if necessary?

Thanks!

**Comment by khalidabuhakmeh** [comment]
Your console has to support Unicode. Have you tried Windows Terminal?

**Comment by ardalis** [comment]
Not yet, I'm guessing that's what you used?

**Comment by ardalis** [comment]
Same issue in Windows Terminal:
![image](https://user-images.githubusercontent.com/782127/80423269-bc69ee00-88ad-11ea-88d1-27dfbda7a1f4.png)

**Comment by ardalis** [comment]
Are you on windows?

**Comment by khalidabuhakmeh** [comment]
I am on macOS. Maybe you have to pick a different encoding. Your font might not be supporting Unicode.
